export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <main>
        <h1 className="font-bold text-3xl">Hello</h1>
      </main>
    </>
  );
}
